# Generated by Django 3.2.4 on 2021-06-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_bm',
            new_name='is_agency_bank',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_co',
            new_name='is_branch_manager',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_sm',
            new_name='is_credit_officer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='is_senior_manager',
            field=models.BooleanField(default=False),
        ),
    ]
