export const allCategories = [
    {
      id: 1,
      name: 'Mobile Devices',
      slug: 'mobile-devices',
      level: 0,
      img: '/mobile-devices.svg',
      sub: [
        {
          id: 1,
          name: 'Mobile phones',
          slug: 'mobile-phones',
          level: 1,
          img: '/mobile-phone.svg',
          sub: [
            {
              id: 1,
              name: 'Andriod phones',
              slug: 'andriod-phones',
              level: 2,
              img: '/android-phone.svg',
              weight: 0.8,
              priceMargin: 1000,
            },
            {
              id: 2,
              name: 'iphone',
              slug: 'iphone',
              level: 2,
              img: '/iphone.svg',
              weight: 1.0,
              priceMargin: 2000,
            },
            {
              id: 3,
              name: 'Tablet and iPads',
              slug: 'tablet-and-ipads',
              level: 2,
              img: '/tablet.svg',
              weight: 1.0,
              priceMargin: 2000,
            },
            {
              id: 4,
              name: 'Basic phones',
              slug: 'basic-phones',
              level: 2,
              img: '/basic-phone.svg',
              weight: 0.6,
              priceMargin: 500,
            },
          ]
        },
        {
          id: 2,
          name: 'Mobile Accessories',
          slug: 'mobile-accessories',
          level: 1,
          img: '/mobile-accessories.svg',
          sub: [
            {
              id: 1,
              name: 'Earphones and Headset',
              slug: 'earphones-and-headset',
              level: 2,
              img: '/earphones-and-headset.svg',
              weight: 0.5,
              priceMargin: 300,
            },
            {
              id: 2,
              name: 'Earpiece',
              slug: 'earpiece',
              level: 2,
              img: '/earpiece.svg',
              weight: 0.2,
              priceMargin: 300,
            },
            {
              id: 3,
              name: 'Airpods and Airdots',
              slug: 'airpods-and-airdots',
              level: 2,
              img: '/airpods-and-airdots.svg',
              weight: 0.5,
              priceMargin: 300,
            },
            {
              id: 4,
              name: 'Bluetooth Speakers',
              slug: 'bluetooth-speakers ',
              level: 2,
              img: '/bluetooth-speakers.svg',
              weight: 0.7,
              priceMargin: 300,
            },
            {
              id: 5,
              name: 'Memory Card',
              slug: 'memory-card',
              level: 2,
              img: '/memory-card.svg',
              weight: 0.50,
              priceMargin: 300,
            },
            {
              id: 6,
              name: 'Powerbank',
              slug: 'powerbank',
              level: 2,
              img: '/powerbank.svg',
              weight: 0.8,
              priceMargin: 300,
            },
            {
              id: 7,
              name: 'Phone Chargers and Phone Adapter ',
              slug: 'phone-chargers-and-phone-adapter',
              level: 2,
              img: '/phone-chargers-and-phone adapter.svg',
              weight: 0.150,
              priceMargin: 300,
            },
            {
              id: 8,
              name: 'Smart Watch',
              slug: 'smart-watch',
              level: 2,
              img: '/smart-watch.svg',
              weight: 0.5,
              priceMargin: 300,
            },
            {
              id: 9,
              name: 'Phone Cases',
              slug: 'phone-cases',
              level: 2,
              img: '/phone-case.svg',
              weight: 0.150,
              priceMargin: 300,
            },
  
          ]
        }
      ]
    },
    {
      id: 2,
      name: 'Fashion',
      slug: 'fashion',
      level: 0,
      img: '/Fashion.svg',
      sub: [
        {
          id: 1,
          name: 'Ladies\' Fashion',
          slug: 'ladies\'-fashion',
          level: 1,
          img: '/ladies-fashion.svg',
          sub: [
            {
              id: 1,
              name: 'Gowns',
              slug: 'gowns',
              level: 2,
              img: '/gowns.svg',
              weight: 0.6,
              priceMargin: 300,
            },
            {
              id: 2,
              name: 'Tops and Blouses',
              slug: 'tops-and-blouses',
              level: 2,
              img: '/tops-and-blouses.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 3,
              name: 'Skirts',
              slug: 'skirts',
              level: 2,
              img: '/skirts.svg',
              weight: 0.4,
              priceMargin: 300,
            },
            {
              id: 4,
              name: 'Ladies\' Trousers',
              slug: 'ladies\'-trousers',
              level: 2,
              img: '/ladies-trousers.svg',
              weight: 0.4,
              priceMargin: 300,
            },
            {
              id: 5,
              name: 'Flat Shoes',
              slug: 'flat-shoes',
              level: 2,
              img: '/flast-shoes.svg',
              weight: 0.5,
              priceMargin: 300,
            },
            {
              id: 6,
              name: 'Ladies\' Sneakers',
              slug: 'ladies\'-sneakers',
              level: 2,
              img: '/ladies-sneakers.svg',
              weight: 0.6,
              priceMargin: 300,
            },
            {
              id: 7,
              name: 'Heels',
              slug: 'heels',
              level: 2,
              img: '/heels.svg',
              weight: 0.7,
              priceMargin: 300,
            },
            {
              id: 8,
              name: 'Ladies\' Slippers and Sandals',
              slug: 'ladies\'-slippers-and-sandals',
              level: 2,
              img: '/ladies-slippers-and-sandals.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 9,
              name: 'Ladies\'Underwear',
              slug: 'ladies\'-underwear',
              level: 2,
              img: '/ladies-underwear.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 10,
              name: 'Sleepwear',
              slug: 'sleepwear',
              level: 2,
              img: '/sleepwear.svg',
              weight: 0.5,
              priceMargin: 300,
            },
            {
              id: 11,
              name: 'Jumpsuit',
              slug: 'jumpsuit',
              level: 2,
              img: '/jumpsuit.svg',
              weight: 0.7,
              priceMargin: 300,
            },
          ]
        },
        {
          id: 2,
          name: 'Men\'s Fashion',
          slug: 'men\'s-fashion',
          level: 1,
          img: '/men-fashion.svg',
          sub: [
            {
              id: 1,
              name: 'Men\'s Polo And T-Shirt',
              slug: 'men\'s-polo-and-tshirt',
              level: 2,
              img: '/men-polo-and-tshirt.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 2,
              name: 'Men\'s Shoes',
              slug: 'men\'s-shoes',
              level: 2,
              img: '/men-shoes.svg',
              weight: 0.7,
              priceMargin: 300,
            },
            {
              id: 3,
              name: 'Men\'s Sneakers',
              slug: 'men\'s-sneakers',
              level: 2,
              img: '/men-sneakers',
              weight: 0.7,
              priceMargin: 300,
            },
            {
              id: 4,
              name: 'Men\'s Slides, slippers and Sandals ',
              slug: 'men\'s-slides-slippers-and-sandals',
              level: 2,
              img: '/men-slides-slippers-and-sandals.svg',
              weight: 0.4,
              priceMargin: 300,
            },
            {
              id: 5,
              name: 'Men\'s Trousers',
              slug: 'men\'s-trousers',
              level: 2,
              img: '/men-trouser.svg',
              weight: 0.6,
              priceMargin: 300,
            },
            {
              id: 6,
              name: 'Men\'s Shirts',
              slug: 'men\'s-shirts',
              level: 2,
              img: '/men-shirt.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 7,
              name: 'Men\'s,Singlets and Inner Shirts ',
              slug: 'men\'s-singlets-and-inner-shirts',
              level: 2,
              img: '/men-singlets-and-inner-shirt.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 8,
              name: 'Men\'s Boxers and Underwear',
              slug: 'men\'s-boxers-and-underwear',
              level: 2,
              img: '/men-boxers-and-underwear',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 9,
              name: 'Hoodies, Jackets and Sweatshirts ',
              slug: 'hoodies-jackets-and-sweatshirts',
              level: 2,
              img: '/hoodies-jackets-and-sweatshirts.svg',
              weight: 0.7,
              priceMargin: 300,
            },
          ]
        },
        {
          id: 3,
          name: 'Fashion Accessories',
          slug: 'fashion-accessories',
          level: 1,
          img: '/fashion-accessories.svg',
          sub: [
            {
              id: 1,
              name: 'Sunglasses',
              slug: 'sunglasses',
              level: 2,
              img: '/sunglasses.svg',
              sub: [
                {
                  id: 1,
                  name: 'Men\'s Sunglasses',
                  slug: 'men\'s-sunglasses',
                  level: 3,
                  img: '/men-sunglasses.svg',
                  weight: 0.2,
                  priceMargin: 300,
                },
                {
                  id: 2,
                  name: 'Ladies\' Sunglasses',
                  slug: 'ladies\'-sunglasses',
                  level: 3,
                  img: '/ladies-sunglasses.svg',
                  weight: 0.2,
                  priceMargin: 300,
                },
              ]
            },
            {
              id: 2,
              name: 'Watches',
              slug: 'watches',
              level: 2,
              img: '/watches.svg',
              sub: [
                {
                  id: 1,
                  name: 'Men\'s Wrist Watch',
                  slug: 'men\'s-wrist-watch',
                  level: 3,
                  img: '/men-wrist-watches.svg',
                  weight: 0.4,
                  priceMargin: 300,
                },
                {
                  id: 2,
                  name: 'Ladies\' Wrist Watch',
                  slug: 'ladies\'-wrist-watch',
                  level: 3,
                  img: '/ladies-wrist-watch.svg',
                  weight: 0.4,
                  priceMargin: 300,
                }
              ]
            },
            {
              id: 3,
              name: 'Jewelry',
              slug: 'Jewelry',
              level: 2,
              img: '/jewelry.svg',
              sub: [
                {
                  id: 1,
                  name: 'Men\'s Jewelry ',
                  slug: 'men\'s-jewelry',
                  level: 3,
                  img: '/men-jewelry.svg',
                  weight: 0.2,
                  priceMargin: 300,
                },
                {
                  id: 2,
                  name: 'Ladies\' Jewlery',
                  slug: 'ladies\'-jewlery',
                  level: 3,
                  img: '/ladies-jewelry.svg',
                  weight: 0.2,
                  priceMargin: 300,
                },
              ]
            },
            {
              id: 4,
              name: 'Belts',
              slug: 'belts',
              level: 2,
              img: "/belts.svg",
              sub: [
                {
                  id: 1,
                  name: 'Men\'s Belt',
                  slug: 'men\'s-belt',
                  level: 3,
                  img: '/men-belt.svg',
                  weight: 0.3,
                  priceMargin: 300,
                },
                {
                  id: 2,
                  name: 'Ladies\' Belt',
                  slug: 'ladies\'-belt',
                  level: 3,
                  img: '/ladies-belt.svg',
                  weight: 0.3,
                  priceMargin: 300,
                },
              ]
            },
            {
              id: 5,
              name: 'Hats,Caps and Headwears ',
              slug: 'hats-caps-and-headwears',
              level: 2,
              img: '/hats-caps-and-headwears.svg',
              sub: [
                {
                  id: 1,
                  name: 'Ladies\' Headwears,Hats and Caps',
                  slug: 'ladies\'-headwears,hats-and-caps',
                  level: 3,
                  img: '/ladies-headwears-hats-and-caps.svg',
                  weight: 0.2,
                  priceMargin: 300,
                },
                {
                  id: 2,
                  name: 'Men\'s Hats,Caps and Headwears',
                  slug: 'men\s-hats,caps-and-headwears',
                  level: 3,
                  img: '/men-hats-caps-and-headwears.svg',
                  weight: 0.3,
                  priceMargin: 300,
                }
              ]
            },
            {
              id: 6,
              name: 'Ties and Cofflinks',
              slug: 'ties-and-cofflinks',
              level: 2,
              img: '/ties-and-cofflinks.svg',
              weight: 0.2,
              priceMargin: 300,
            }
          ]
        },
        {
          id: 4,
          name: 'Bags and Handbags',
          slug: 'bags-and-handbags',
          level: 1,
          img: '/bags-and-handbags.svg',
          sub: [
            {
              id: 1,
              name: 'Laptop Bags',
              slug: 'laptop-bags',
              level: 2,
              img: '/laptop-bags.svg',
              weight: 0.8,
              priceMargin: 300,
            },
            {
              id: 2,
              name: 'Small Handbags and Purse',
              slug: 'small-handbags-and-purse',
              level: 2,
              img: '/small-handbags-and-purse.svg',
              weight: 0.5,
              priceMargin: 300,
            },
            {
              id: 3,
              name: 'Big Handbags and Backpack Bags',
              slug: 'big-handbags-and-backpack-bags',
              level: 2,
              img: '/big-handbags-and-backpack-bags',
              weight: 0.8,
              priceMargin: 500,
            },
            {
              id: 4,
              name: 'Travelling Bags',
              slug: 'travelling-bags',
              level: 2,
              img: '/travelling-bags.svg',
              weight: 1.5,
              priceMargin: 1000,
            },
            {
              id: 5,
              name: 'School Bags',
              slug: 'school-bags',
              level: 2,
              img: '/school-bags',
              weight: 0.6,
              priceMargin: 300,
            },
            {
              id: 6,
              name: 'Wallets, Mens Handbags and Crossbody Bags',
              slug: 'wallets-men’s-handbags-and-crossbody-bags',
              level: 2,
              img: '/wallets-men’s-handbags-and-crossbody-bags.svg',
              weight: 0.5,
              priceMargin: 300,
            },
          ]
        },
        {
          id: 5,
          name: 'Sports Wears',
          slug: 'sports-wears',
          level: 1,
          img: "/sports-wear.svg",
          sub: [
            {
              id: 1,
              name: 'Soccer Boots',
              slug: 'soccer-boots',
              level: 2,
              img: '/soccer-boots.svg',
              weight: 0.7,
              priceMargin: 500,
            },
            {
              id: 2,
              name: 'Running Shoes',
              slug: 'running-shoes',
              level: 2,
              img: '/running-shoes.svg',
              weight: 0.7,
              priceMargin: 500,
            },
            {
              id: 3,
              name: 'Football Jersey',
              slug: 'football-jersey',
              level: 2,
              img: '/football-jersey.svg',
              weight: 0.4,
              priceMargin: 300,
            },
            {
              id: 4,
              name: 'Joggers',
              slug: 'joggers',
              level: 2,
              img: '/joggers.svg',
              weight: 0.6,
              priceMargin: 300,
            },
            {
              id: 5,
              name: 'Tracksuits',
              slug: 'tracksuits',
              level: 2,
              img: '/tracksuits',
              weight: 0.7,
              priceMargin: 300,
            }
          ]
        }
      ]
    },
    {
      id: 3,
      name: 'Health and Beauty',
      slug: 'health-and-beauty',
      level: 0,
      img: '/health-and-beauty.svg',
      sub: [
        {
          id: 1,
          name: 'Hair Care',
          slug: 'hair-care',
          level: 1,
          img: '/hair-care.svg',
          sub: [
            {
              id: 1,
              name: 'Hair and Scalp Care',
              slug: 'hair-and-scalp-care',
              level: 2,
              img: '/hair-and-scalp-care.svg',
              weight: 0.4,
              priceMargin: 200,
            },
            {
              id: 2,
              name: 'Hair Cutting Tools',
              slug: 'hair-cutting-tools',
              level: 2,
              img: '/hair-cutting-tools.svg',
              weight: 0.7,
              priceMargin: 300,
            },
            {
              id: 3,
              name: 'Shampoo and Conditioner',
              slug: 'shampoo-and-coditioner',
              level: 2,
              img: '/shampoo-and-coditioner.svg',
              weight: 0.4,
              priceMargin: 200,
            },
            {
              id: 4,
              name: 'Wigs and Weaves',
              slug: 'wigs-and-weaves',
              level: 2,
              img: '/wigs-and-weaves.svg',
              weight: 0.8,
              priceMargin: 300,
            },
            {
              id: 5,
              name: 'Hair Attachement',
              slug: 'hair-attachement',
              level: 2,
              img: '/hair-attachement',
              weight: 0.8,
              priceMargin: 500,
            },
            {
              id: 6,
              name: 'Closures',
              slug: 'closures',
              level: 2,
              img: '/closures.svg',
              weight: 0.4,
              priceMargin: 300,
            },
          ]
        },
        {
          id: 2,
          name: 'Make Up',
          slug: 'make-up',
          level: 1,
          img: '/make-up.svg',
          sub: [
            {
              id: 1,
              name: 'Foundation, Powder, Concealers and Colour Correctors ',
              slug: 'foundation-powder-concealers-and-colour-correctors',
              level: 2,
              img: '/foundation-powder.svg',
              weight: 0.4,
              priceMargin: 300,
            },
            {
              id: 2,
              name: 'Lip Gloss, Lip Liner and Lipstick',
              slug: 'lip-gloss-lip-liner-and-lipstick',
              level: 2,
              img: '/lip-gloss-lip-liner.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 3,
              name: 'Eyeliner, Eyeshadow and Mascara',
              slug: 'eyeliner-eyeshadow-and-mascara',
              level: 2,
              img: '/eyeliner-eyeshadow.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 4,
              name: 'Make Up Brushes',
              slug: 'make-up-brushes',
              level: 2,
              img: '/make-up-brushes.svg',
              weight: 0.2,
              priceMargin: 300,
            }
          ]
        },
        {
          id: 3,
          name: 'Healthcare',
          slug: 'healthcare',
          level: 1,
          img: '/healthcare.svg',
          sub: [
            {
              id: 1,
              name: 'Face Masks and Protection',
              slug: 'face-masks-and-protection',
              level: 2,
              img: '/face-mask.svg',
              weight: 0.2,
              priceMargin: 300,
            },
            {
              id: 2,
              name: 'Thermometer',
              slug: 'thermometer',
              level: 2,
              img: '/thermometer.svg',
              weight: 0.8,
              priceMargin: 500,
            },
            {
              id: 3,
              name: 'Hand Sanitizers',
              slug: 'hand-sanitizers',
              level: 2,
              img: '/hand-sanitizer.svg',
              weight: 0.8,
              priceMargin: 300,
            },
  
            {
              id: 4,
              name: 'Lab safety Gloves',
              slug: 'lab-safety-gloves',
              level: 2,
              img: '/lab-safety-gloves.svg',
              weight: 0.1,
              priceMargin: 300,
            },
            {
              id: 5,
              name: 'Work Gloves',
              slug: 'work-gloves',
              level: 2,
              img: '/work-gloves.svg',
              weight: 0.1,
              priceMargin: 300,
            },
          ]
        },
        {
          id: 4,
          name: 'Fragrances',
          slug: 'frangrances',
          level: 1,
          img: '/frangrances.svg',
          sub: [
            {
              id: 1,
              name: 'Ladies\' Perfumes and Perfume Oil',
              slug: 'ladies\'-perfumes-and-perfume-oil',
              level: 2,
              img: '/ladies-perfumes.svg',
              weight: 0.5,
              priceMargin: 300,
            },
            {
              id: 2,
              name: 'Men\'s Perfume and Perfume Oil',
              slug: 'men\'s-perfume-and-perfume-oil',
              level: 2,
              img: '/men-perfume.svg',
              weight: 0.5,
              priceMargin: 300,
            },
            {
              id: 3,
              name: 'Body Sprays',
              slug: 'body-sprays',
              level: 2,
              img: '/body-spray.svg',
              weight: 0.4,
              priceMargin: 300,
            }
          ]
        },
        {
          id: 5,
          name: 'Body Care',
          slug: 'body care',
          level: 1,
          img: '/body-care.svg',
          sub: [
            {
              id: 1,
              name: 'Body Lotion and Cream',
              slug: 'body-lotion-and-cream',
              level: 2,
              img: '/body-care.svg',
              weight: 0.4,
              priceMargin: 300,
            },
            {
              id: 2,
              name: 'Soap, Bath and Shower Gels',
              lug: 'soap-bath-and-shower-gels',
              level: 2,
              img: '/soap-bath-shower-gel',
              weight: 0.3,
              priceMargin: 300,
            },
          ]
        }
      ]
    },
    {
      id: 4,
      name: 'Laptops and Accessories',
      slug: 'laptops-and-accessories',
      level: 0,
      img: '/laptop-and-accessories.svg',
      sub: [
        {
          id: 1,
          name: 'Laptops',
          slug: 'laptops',
          level: 1,
          img: '/laptops.svg',
          sub: [
            {
              id: 1,
              name: 'Window Laptops',
              slug: 'window-laptops',
              level: 2,
              img: '/window-laptops.svg',
              weight: 2.5,
              priceMargin: 2000,
            },
            {
              id: 2,
              name: 'MacBook',
              slug: 'macbook',
              level: 2,
              img: '/macbook.svg',
              weight: 2.0,
              priceMargin: 2000,
            }
          ]
        },
        {
          id: 2,
          name: 'Laptops Accessories',
          slug: 'laptops-accessories',
          level: 1,
          img: '/laptop-accessories.svg',
          sub: [
            {
              id: 1,
              name: 'Mouse',
              slug: 'mouse',
              level: 2,
              img: '/mouse.svg',
              weight: 0.2,
              priceMargin: 300,
            },
            {
              id: 2,
              name: 'Keyboards',
              slug: 'keyboards',
              level: 2,
              img: '/keyboards.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 3,
              name: 'Hard Drives',
              slug: 'hard-drives',
              level: 2,
              img: '/hard-drives.svg',
              weight: 0.5,
              priceMargin: 300,
            },
            {
              id: 4,
              name: 'Flash Drives',
              slug: 'flash-drives',
              level: 2,
              img: '/flash-drives.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 5,
              name: 'Printers and Scanners',
              slug: 'printers-and-scanners',
              level: 2,
              img: '/printers-and-scanners.svg',
              weight: 3.0,
              priceMargin: 2000,
            },
            {
              id: 6,
              name: 'Laptop Batteries',
              slug: 'laptop-batteries',
              level: 2,
              img: '/laptop-batteries.svg',
              weight: 0.7,
              priceMargin: 500,
            },
            {
              id: 7,
              name: 'Antivirus and Security',
              slug: 'antivirus-and-security',
              level: 2,
              img: '/antivirus-and-security.svg',
              weight: 0.3,
              priceMargin: 300,
            },
            {
              id: 8,
              name: 'Laptop Chargers',
              slug: 'laptop-chargers',
              level: 2,
              img: '/laptop-chargers.svg',
              weight: 0.4,
              priceMargin: 300,
            },
            {
              id: 9,
              name: 'Computer Speakers',
              slug: 'computer-speakers',
              level: 2,
              img: '/computer-speakers.svg',
              weight: 0.8,
              priceMargin: 300,
            }
          ]
        },
      ]
    },
    {
      id: 5,
      name: 'Packaging Materials and Souvenirs',
      slug: 'packaging-materials-and-souvenirs',
      level: 0,
      img: '/packagin-materials-and-souvenirs.svg',
      sub: [
        {
          id: 1,
          name: 'Nylons',
          slug: 'nylons',
          level: 1,
          img: '/nylons.svg',
          sub: [
            {
              id: 1,
              name: 'Small Nylons',
              slug: 'small-nylons',
              level: 2,
              img: '/small-nylons.svg',
              weight: 0.10,
              priceMargin: 50,
            },
            {
              id: 2,
              name: 'Medium Nylons',
              slug: 'medium-nylons',
              level: 2,
              img: '/medium-nylons.svg',
              weight: 0.20,
              priceMargin: 50,
            },
            {
              id: 3,
              name: 'Large Nylons',
              slug: 'large-nylons',
              level: 2,
              img: '/large-nylons.svg',
              weight: 0.50,
              priceMargin: 50,
            }
          ]
        },
        {
          id: 2,
          name: 'Mailing Bags',
          slug: 'mailing-bags',
          level: 1,
          img: '/mailing-bags.svg',
          sub: [
            {
              id: 1,
              name: 'Small Mailing Bags',
              slug: 'small-mailing-bags',
              level: 2,
              img: '/small-mailing-bags.svg',
              weight: 0.20,
              priceMargin: 100,
            },
            {
              id: 2,
              name: 'Medium Mailing Bags',
              slug: 'medium-mailing-bags',
              level: 2,
              img: '/medium-mailing-bags.svg',
              weight: 0.50,
              priceMargin: 100,
            },
            {
              id: 3,
              name: 'Big Mailing Bags',
              slug: 'big-mailing-bags',
              level: 2,
              img: '/big-mailing-bags.svg',
              weight: 0.80,
              priceMargin: 100,
            }
          ]
        },
        {
          id: 3,
          name: 'Paper Bags',
          slug: 'paper-bags',
          level: 1,
          img: '/paper-bags.svg',
          sub: [
            {
              id: 1,
              name: 'Small Paper Bags',
              slug: 'small-paper-bags',
              level: 2,
              img: '/small-paper-bags.svg',
              weight: 0.10,
              priceMargin: 50,
            },
            {
              id: 2,
              name: 'Medium Paper Bags',
              slug: 'medium-paper-bags',
              level: 2,
              img: '/medium-paper-bags.svg',
              weight: 0.30,
              priceMargin: 50,
            },
            {
              id: 3,
              name: 'Large Paper Bags',
              slug: 'large-paper-bags',
              level: 2,
              img: '/large-paper-bags.svg',
              weight: 0.60,
              priceMargin: 50,
            }
          ]
        },
        {
          id: 4,
          name: 'Packaging Boxes and Cases',
          slug: 'packaging-boxes-and-cases',
          level: 1,
          img: '/packaging-boxes-and-cases.svg',
          sub: [
            {
              id: 1,
              name: 'Small Boxes and Cases',
              slug: 'small-boxes-and-cases',
              level: 2,
              img: '/small-boxes-and-cases.svg',
              weight: 2.0,
              priceMargin: 1000,
            },
            {
              id: 2,
              name: 'Medium Boxes and Cases',
              slug: 'medium-boxes-and-cases',
              level: 2,
              img: '/medium-boxes-and-cases.svg',
              weight: 3.0,
              priceMargin: 1500,
            },
            {
              id: 3,
              name: 'Large Boxes and Cases',
              slug: 'large-boxes-and-cases',
              level: 2,
              img: '/large-boxes-and-cases.svg',
              weight: 3.5,
              priceMargin: 2000,
            }
          ]
        },
        {
          id: 5,
          name: 'Food Packs',
          slug: 'food-packs',
          level: 1,
          img: '/food-packs.svg',
          sub: [
            {
              id: 1,
              name: 'Disposable Food Packs',
              slug: 'disposable-food-packs',
              level: 2,
              img: '/disposable-food-packs',
              weight: 0.10,
              priceMargin: 50,
            },
            {
              id: 2,
              name: 'Reusable Plastics Plates',
              slug: 'reusable-plastics-plates',
              level: 2,
              img: '/reusable-plastics-plates',
              weight: 0.20,
              priceMargin: 50,
            },
            {
              id: 3,
              name: 'Food Trays',
              slug: 'food-trays',
              level: 2,
              img: '/food-trays.svg',
              weight: 0.1,
              priceMargin: 100,
            },
            {
              id: 4,
              name: 'Disposable Cups',
              slug: 'disposable-cups',
              level: 2,
              img: '/disposable-cups.svg',
              weight: 0.1,
              priceMargin: 100,
            }
          ]
        },
        {
          id: 6,
          name: 'Thank You Cards',
          slug: 'thank-you-cards',
          level: 1,
          img: '/thank-you-cards.svg',
          Weight: 0.10,
          Pricemargin: 100
        },
        {
          id: 7,
          name: 'Stationery and Writting Materials',
          slug: 'stationery-and-writting materials',
          level: 1,
          img: '/stationery-and-writing-materials.svg',
          sub: [
            {
              id: 1,
              name: 'Envelops',
              slug: 'envelops',
              level: 2,
              img: '/evelops.svg',
              weight: 0.10,
              priceMargin: 50,
            },
            {
              id: 2,
              name: 'Pens and Pencils',
              slug: 'pens-and-pencils',
              level: 2,
              img: '/pens-and-pencils.svg',
              weight: 0.10,
              priceMargin: 50,
            },
            {
              id: 3,
              name: 'Markers',
              slug: 'markers',
              level: 2,
              img: '/markers.svg',
              weight: 0.50,
              priceMargin: 50,
            },
            {
              id: 4,
              name: 'Printing Papers',
              slug: 'printing-papers',
              level: 2,
              img: '/printing-papers.svg',
              weight: 1.0,
              priceMargin: 500,
            }
          ]
        },
        {
          id: 8,
          name: 'Books and Jotter',
          slug: 'books-and-jotter',
          level: 1,
          img: '/books-and-jotter.svg',
          sub: [
            {
              id: 1,
              name: 'Note Books',
              slug: 'note-books',
              level: 2,
              img: '/note-books.svg',
              weight: 0.3,
              priceMargin: 50,
            },
            {
              id: 2,
              name: 'Jotters',
              slug: 'jotters',
              level: 2,
              img: '/jotters.svg',
              weight: 0.2,
              priceMargin: 50,
            },
            {
              id: 3,
              name: 'Dairies and Planners',
              slug: 'dairies-and-planners',
              level: 2,
              img: '/dairies-and-planners.svg',
              weight: 0.5,
              priceMargin: 200,
            },
            {
              id: 4,
              name: 'Hardcover and Notebooks',
              slug: 'hardcover-and-notebooks',
              level: 2,
              img: '/hardcover-and-notebooks.svg',
              weight: 0.2,
              priceMargin: 100,
            }
          ]
        }
      ]
    },
    {
      id: 6,
      name: 'Others',
      slug: 'Others',
      level: 0,
      img: '/others.svg',
      sub: [
        {
          id: 1,
          name: 'Gaming Accessories',
          slug: 'gaming-accessories',
          level: 1,
          img: '/gaming-accessories.svg',
          sub: [
            {
              id: 1,
              name: 'Gaming Pad',
              slug: 'gaming-pad',
              level: 2,
              img: '/gaming-pad.svg',
              weight: 0.7,
              priceMargin: 400,
            },
            {
              id: 2,
              name: 'Gaming Consoles',
              slug: 'gaming-consoles',
              level: 2,
              img: '/gaming-consoles.svg',
              weight: 3.0,
              priceMargin: 1500,
            },
            {
              id: 3,
              name: 'Memory card and External Devices',
              slug: 'memory-card-and-external-devices',
              level: 2,
              img: '/memory-card-and-external-devices.svg',
              weight: 0.5,
              priceMargin: 300,
            }
          ]
        },
        {
          id: 2,
          name: 'Beddings',
          slug: 'beddings',
          level: 1,
          img: '/beddings.svg',
          sub: [
            {
              id: 1,
              name: 'Bedsheets and Pillow case',
              slug: 'bedsheets-and-pillow-case',
              level: 2,
              img: '/bedsheets-and-pillow-case.svg',
              weight: 0.8,
              priceMargin: 500,
            },
            {
              id: 2,
              name: 'Blankets and Dulvets',
              slug: 'blankets-and-dulvets',
              level: 2,
              img: '/blankets-and-dulvets.svg',
              weight: 2.0,
              priceMargin: 500,
            }
          ]
        },
        {
          id: 3,
          name: 'Kitchen Utensils',
          slug: 'kitchen-utensils',
          level: 1,
          img: '/kitchen-utensils.svg',
          sub: [
            {
              id: 1,
              name: 'Cooking Pots',
              slug: 'cooking-pots',
              level: 2,
              img: '/cooking-pots.svg',
              weight: 2.0,
              priceMargin: 500,
            },
            {
              id: 2,
              name: 'Plates and Spoons',
              slug: 'plates-and-spoons',
              level: 2,
              img: '/plates-and-spoons.svg',
              weight: 0.4,
              priceMargin: 300,
            },
            {
              id: 3,
              name: 'Burner and Cooking Gadjets',
              slug: 'burner-and-cooking-gadjets',
              level: 2,
              img: '/burner-and-cooking-gadjets.svg',
              weight: 3.0,
              priceMargin: 1000,
            }
          ]
        }
      ]
    }
  ]